runtime: nodejs22
env: standard
instance_class: F1
entrypoint: npm start

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  MONGODB_URI: "mongodb+srv://shahid:ns2009517@cluster1.zsjwipv.mongodb.net"
  JWT_SECRET: "hello@secret"
  NODE_ENV: "production"
  CLOUDINARY_CLOUD_NAME: "du4sa4q9j"
  CLOUDINARY_API_KEY: "524198393247422"
  CLOUDINARY_API_SECRET: "8NB-prOo-XQpkr8Ivb0fgwr_zO8"
  RAZORPAY_KEY_ID: rzp_test_Z9tMkNPDmGLQsB
  RAZORPAY_KEY_SECRET: IQycldxMltpQE7Ay2fUaNOeu
  CATEGORY_ID: 684d02ce88b46b39fb4fc009
  MAIL_USER: "90e56e003@smtp-brevo.com"
  MAIL_PASS: "h7cBg6aSvIX8CDOH"
  SENDER_EMAIL: "shopease00000@gmail.com"
  CLIENT_URL: http://localhost:5173
